// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// CampaignRule is the golang structure for table campaign_rule.
type CampaignRule internal.CampaignRule

// Fill with you ideas below.