// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// Campaign is the golang structure for table campaign.
type Campaign internal.Campaign

// Fill with you ideas below.