// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import(
"github.com/gogf/gf/os/gtime"
)


// FeadSubscription is the golang structure for table fead_subscription.
type FeadSubscription struct {
    Id                    uint        `orm:"id,primary"              json:"id"`                    //                                                        
    ProfileId             int64       `orm:"profile_id"              json:"profileId"`             // Profile ID                                             
    DatasetId             string      `orm:"dataset_id"              json:"datasetId"`             // 订阅的数据类型：sp-traffic,sp-conversion,budget-usage  
    MessageSubscriptionId string      `orm:"message_subscription_id" json:"messageSubscriptionId"` // 消息订阅id                                             
    CreateDate            *gtime.Time `orm:"create_date"             json:"createDate"`            // 创建时间                                               
    Status                int         `orm:"status"                  json:"status"`                // 整体是否：1有效 0 无效                                 
    ErrReason             string      `orm:"err_reason"              json:"errReason"`             // 如果错误，记录失败原因                                 
    SqsName               string      `orm:"sqs_name"                json:"sqsName"`               // SQS名称                                                
    SqsArn                string      `orm:"sqs_arn"                 json:"sqsArn"`                // SQS的识别符                                            
    SqsStatus             string      `orm:"sqs_status"              json:"sqsStatus"`             // SQS状态                                                
    IsDel                 int         `orm:"is_del"                  json:"isDel"`                 // 删除标记，1为删除                                      
}