// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// Fead is the golang structure for table fead.
type Fead internal.Fead

// Fill with you ideas below.