// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// Profile is the golang structure for table profile.
type Profile internal.Profile

// Fill with you ideas below.