// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// ReportCheckRetryDetail is the golang structure for table report_check_retry_detail.
type ReportCheckRetryDetail internal.ReportCheckRetryDetail

// Fill with you ideas below.