// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// ReportSbConsumerDetail is the golang structure for table report_sb_consumer_detail.
type ReportSbConsumerDetail internal.ReportSbConsumerDetail

// Fill with you ideas below.