// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// ReportSchdule is the golang structure for table report_schdule.
type ReportSchdule internal.ReportSchdule

// Fill with you ideas below.