// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// ReportBatch is the golang structure for table report_batch.
type ReportBatch internal.ReportBatch

// Fill with you ideas below.