// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// ReportCheck is the golang structure for table report_check.
type ReportCheck internal.ReportCheck

// Fill with you ideas below.