// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// ReportDspConsumerDetail is the golang structure for table report_dsp_consumer_detail.
type ReportDspConsumerDetail internal.ReportDspConsumerDetail

// Fill with you ideas below.