// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// ReportTask is the golang structure for table report_task.
type ReportTask internal.ReportTask

// Fill with you ideas below.