// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// ReportSdConsumerDetail is the golang structure for table report_sd_consumer_detail.
type ReportSdConsumerDetail internal.ReportSdConsumerDetail

// Fill with you ideas below.