// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// ReportDspCheck is the golang structure for table report_dsp_check.
type ReportDspCheck internal.ReportDspCheck

// Fill with you ideas below.