// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// ReportSpCheck is the golang structure for table report_sp_check.
type ReportSpCheck internal.ReportSpCheck

// Fill with you ideas below.