// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// ReportSpConsumerDetail is the golang structure for table report_sp_consumer_detail.
type ReportSpConsumerDetail internal.ReportSpConsumerDetail

// Fill with you ideas below.