// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// ReportSbCheck is the golang structure for table report_sb_check.
type ReportSbCheck internal.ReportSbCheck

// Fill with you ideas below.