// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// ReportBatchDetail is the golang structure for table report_batch_detail.
type ReportBatchDetail internal.ReportBatchDetail

// Fill with you ideas below.