// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"td_report/app/model/internal"
)

// SpTraffic is the golang structure for table sp_traffic.
type SpTraffic internal.SpTraffic

// Fill with you ideas below.