// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// CampaignRule is the golang structure for table campaign_rule.
type CampaignRule struct {
    Id         uint        `orm:"id,primary" json:"id"`         //                             
    CampaignId int         `orm:"campaignId" json:"campaignId"` //                             
    AdGroupId  uint64      `orm:"adGroupId"  json:"adGroupId"`  // adGroupId                   
    StartDate  int64       `orm:"startDate"  json:"startDate"`  //                             
    EndDate    int64       `orm:"endDate"    json:"endDate"`    //                             
    RuleName   string      `orm:"ruleName"   json:"ruleName"`   //                             
    RuleType   uint        `orm:"ruleType"   json:"ruleType"`   //                             
    TemplateId int         `orm:"templateId" json:"templateId"` //                             
    Condition  string      `orm:"condition"  json:"condition"`  //                             
    Status     int         `orm:"status"     json:"status"`     // 规则默认开启1，关闭0,归档2  
    Result     string      `orm:"result"     json:"result"`     //                             
    Action     string      `orm:"action"     json:"action"`     //                             
    CreatedAt  *gtime.Time `orm:"createdAt"  json:"createdAt"`  //                             
    LastUpdate *gtime.Time `orm:"lastUpdate" json:"lastUpdate"` //                             
}