// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Campaign is the golang structure for table campaign.
type Campaign struct {
    Id                    uint        `orm:"id,primary"            json:"id"`                    // 主键ID                                                
    AmazonCampaignId      int64       `orm:"amazonCampaignId"      json:"amazonCampaignId"`      // 亚马逊主键ID                                          
    ProfileId             int64       `orm:"profileId"             json:"profileId"`             // ProfileID                                             
    AmazonPortfolioId     int64       `orm:"amazonPortfolioId"     json:"amazonPortfolioId"`     // 亚马逊PortfolioId                                     
    Name                  string      `orm:"name"                  json:"name"`                  // 活动名称                                              
    CampaignType          string      `orm:"campaignType"          json:"campaignType"`          // 活动类型(sponsoredProducts,sponsoredDisplay)          
    Tactic                string      `orm:"tactic"                json:"tactic"`                // 策略                                                  
    TargetingType         string      `orm:"targetingType"         json:"targetingType"`         // 目标类型                                              
    State                 string      `orm:"state"                 json:"state"`                 // 广告组状态(enabled:可用;paused:暂停;archived:已归档)  
    BudgetType            string      `orm:"budgetType"            json:"budgetType"`            // 预算类型                                              
    DailyBudget           float64     `orm:"dailyBudget"           json:"dailyBudget"`           // 每日预算                                              
    AdFormat              string      `orm:"adFormat"              json:"adFormat"`              // sb广告类型                                            
    StartDate             int         `orm:"startDate"             json:"startDate"`             // 开始时间                                              
    EndDate               int         `orm:"endDate"               json:"endDate"`               // 结束时间                                              
    BrandEntityId         string      `orm:"brandEntityId"         json:"brandEntityId"`         // sb 品牌entityId                                       
    PremiumBidAdjustment  int         `orm:"premiumBidAdjustment"  json:"premiumBidAdjustment"`  // 溢价投标调整                                          
    BiddingStrategy       string      `orm:"biddingStrategy"       json:"biddingStrategy"`       // 投标策略                                              
    TopAdjustment         float64     `orm:"topAdjustment"         json:"topAdjustment"`         // 顶部广告位竞价调整                                    
    ProductPageAdjustment float64     `orm:"productPageAdjustment" json:"productPageAdjustment"` // 产品页面调整                                          
    Status                int         `orm:"status"                json:"status"`                // 状态(0:正常;1:禁用)                                   
    AutoStatus            uint        `orm:"autoStatus"            json:"autoStatus"`            // 智能优化开关                                          
    ServingStatus         string      `orm:"servingStatus"         json:"servingStatus"`         // 服务状态                                              
    CostType              string      `orm:"costType"              json:"costType"`              // 成本类型展示                                          
    CreatedAt             *gtime.Time `orm:"createdAt"             json:"createdAt"`             //                                                       
    LastUpdate            *gtime.Time `orm:"lastUpdate"            json:"lastUpdate"`            //                                                       
    LastUpdateTs          uint        `orm:"lastUpdateTs"          json:"lastUpdateTs"`          // 最后更新时间戳                                        
    IsSync                int         `orm:"isSync"                json:"isSync"`                // 同步状态(0:待同步;1:已同步)                           
    LastSync              uint        `orm:"lastSync"              json:"lastSync"`              // 上次同步时间戳                                        
    BidOptimization       int         `orm:"bidOptimization"       json:"bidOptimization"`       // 0:false 1:true                                        
    BidMultiplier         float64     `orm:"bidMultiplier"         json:"bidMultiplier"`         // sb出价系数                                            
}