// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Fead is the golang structure for table fead.
type Fead struct {
    Id                     uint        `orm:"id,primary"               json:"id"`                     //                                       
    ProfileId              int64       `orm:"profile_id"               json:"profileId"`              //                                       
    DatasetId              string      `orm:"dataset_id"               json:"datasetId"`              //                                       
    CreateDate             *gtime.Time `orm:"create_date"              json:"createDate"`             //                                       
    Status                 int         `orm:"status"                   json:"status"`                 // 整体是否：1有效 0 无效                
    Step                   int         `orm:"step"                     json:"step"`                   // 授权进行到哪一步，一共3步             
    StepStatus             int         `orm:"step_status"              json:"stepStatus"`             // 进行到哪一步的单独的状态1有效 0 无效  
    ErrReason              string      `orm:"err_reason"               json:"errReason"`              // 如果错误，记录失败原因                
    UpdateDate             *gtime.Time `orm:"update_date"              json:"updateDate"`             //                                       
    ClientTokenId          string      `orm:"client_token_id"          json:"clientTokenId"`          // 订阅后的参数，针对队列有用            
    MessagesSubscriptionId string      `orm:"messages_subscription_id" json:"messagesSubscriptionId"` // 订阅后的参数，针对队列有用            
    Version                float64     `orm:"version"                  json:"version"`                // 订阅后参数，版本后针对队列排查问题    
}