// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// ReportBatchDetail is the golang structure for table report_batch_detail.
type ReportBatchDetail struct {
    Id             uint        `orm:"id,primary"       json:"id"`             //                           
    Batch          string      `orm:"batch"            json:"batch"`          // 批次号，关联report_batch  
    ReportNameList string      `orm:"report_name_list" json:"reportNameList"` // 同步的报表名称            
    ReportType     string      `orm:"report_type"      json:"reportType"`     //                           
    StartDate      *gtime.Time `orm:"start_date"       json:"startDate"`      //                           
    EndDate        *gtime.Time `orm:"end_date"         json:"endDate"`        //                           
    Status         int         `orm:"status"           json:"status"`         // 1 执行中 2 完成 3 错误    
    CreateDate     *gtime.Time `orm:"create_date"      json:"createDate"`     //                           
    UpdateDate     *gtime.Time `orm:"update_date"      json:"updateDate"`     //                           
    Reason         string      `orm:"reason"           json:"reason"`         //                           
}