// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// ReportTask is the golang structure for table report_task.
type ReportTask struct {
    Id         int64       `orm:"id,primary"  json:"id"`         //                                                                                   
    ReportDate string      `orm:"report_date" json:"reportDate"` //                                                                                   
    IsFull     int         `orm:"is_full"     json:"isFull"`     // 1,0                                                                               
    AdPlatform string      `orm:"ad_platform" json:"adPlatform"` // amazon,google,facebook                                                            
    ReportType string      `orm:"report_type" json:"reportType"` // sp,sd,dsp                                                                         
    TaskType   string      `orm:"task_type"   json:"taskType"`   // audience,detail,inventory,order,target,ad_group,product_ad,campaign,asin,keyword  
    TaskStatus string      `orm:"task_status" json:"taskStatus"` // initializing,pending,running,succeeded,task_failed,result_wrong                   
    TimePeriod string      `orm:"time_period" json:"timePeriod"` // day,month                                                                         
    DataPath   string      `orm:"data_path"   json:"dataPath"`   //                                                                                   
    LastUpdate *gtime.Time `orm:"lastUpdate"  json:"lastUpdate"` //                                                                                   
}