// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// ReportSpCheck is the golang structure for table report_sp_check.
type ReportSpCheck struct {
    Id             string      `orm:"id,primary"      json:"id"`             //                  
    ReportName     string      `orm:"report_name"     json:"reportName"`     //                  
    ReportDate     *gtime.Time `orm:"report_date"     json:"reportDate"`     //                  
    ProfileId      string      `orm:"profile_id"      json:"profileId"`      //                  
    Filename       string      `orm:"filename"        json:"filename"`       //                  
    FileChangedate string      `orm:"file_changedate" json:"fileChangedate"` // 文件更新时间     
    Status         int         `orm:"status"          json:"status"`         // 0 不存在 1 存在  
    Createdate     *gtime.Time `orm:"createdate"      json:"createdate"`     //                  
    Updatedate     *gtime.Time `orm:"updatedate"      json:"updatedate"`     //                  
}