// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// ReportError is the golang structure for table report_error.
type ReportError struct {
    Id          string      `orm:"id,primary"   json:"id"`          //                                                
    ErrorType   int         `orm:"error_type"   json:"errorType"`   // 错误类型                                       
    ErrorReason string      `orm:"error_reason" json:"errorReason"` // 错误信息                                       
    KeyParamas  string      `orm:"key_paramas"  json:"keyParamas"`  // 关键参数json,除部分参数明确外其他的不明确参数  
    CreateDate  *gtime.Time `orm:"create_date"  json:"createDate"`  //                                                
    ReportType  string      `orm:"report_type"  json:"reportType"`  //                                                
    ReportName  string      `orm:"report_name"  json:"reportName"`  //                                                
    ReportDate  string      `orm:"report_date"  json:"reportDate"`  //                                                
    ProfileId   string      `orm:"profile_id"   json:"profileId"`   //                                                
    Extrant     string      `orm:"extrant"      json:"extrant"`     // 额外类别，区分sd的t200 ,t300等                 
}