// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SellerClient is the golang structure for table seller_client.
type SellerClient struct {
    Id           int         `orm:"id,primary"   json:"id"`           //                                       
    ClientId     string      `orm:"clientId"     json:"clientId"`     //                                       
    ClientSecret string      `orm:"clientSecret" json:"clientSecret"` //                                       
    IsCurrent    int         `orm:"isCurrent"    json:"isCurrent"`    // 新授权使用标记, 1-正在使用, 0-未使用  
    CreatedAt    *gtime.Time `orm:"createdAt"    json:"createdAt"`    //                                       
    LastUpdate   *gtime.Time `orm:"lastUpdate"   json:"lastUpdate"`   //
}