// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SellerProfile is the golang structure for table seller_profile.
type SellerProfile struct {
    Id                  int64       `orm:"id,primary"          json:"id"`                  // 自增ID                             
    TokenId             int         `orm:"tokenId"             json:"tokenId"`             // TokenID                            
    Region              string      `orm:"region"              json:"region"`              // 地区(NA:美区;EU:欧区;FE:日韩区)    
    ProfileId           int64       `orm:"profileId"           json:"profileId"`           // ProfileID                          
    EntityName          string      `orm:"entityName"          json:"entityName"`          // 实体名称                           
    DspProfileId        uint64      `orm:"dspProfileId"        json:"dspProfileId"`        // DSP profileId                      
    DspAdvertiserId     uint64      `orm:"dspAdvertiserId"     json:"dspAdvertiserId"`     // DSP advertiserId                   
    CountryCode         string      `orm:"countryCode"         json:"countryCode"`         // 国家代码                           
    CurrencyCode        string      `orm:"currencyCode"        json:"currencyCode"`        // 货币代码                           
    Timezone            string      `orm:"timezone"            json:"timezone"`            // 时区                               
    MarketplaceStringId string      `orm:"marketplaceStringId" json:"marketplaceStringId"` //                                    
    EntityId            string      `orm:"entityId"            json:"entityId"`            // 实体ID                             
    Type                string      `orm:"type"                json:"type"`                // 类型(seller:经销商;agency:代理商)  
    IsAuto              int         `orm:"isAuto"              json:"isAuto"`              //                                    
    Status              int         `orm:"status"              json:"status"`              // 状态(0:正常;1:禁用)                
    CreatedAt           *gtime.Time `orm:"createdAt"           json:"createdAt"`           // 最后更新时间                       
    LastUpdate          *gtime.Time `orm:"lastUpdate"          json:"lastUpdate"`          // 同步状态                           
}