// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SpTraffic is the golang structure for table sp_traffic.
type SpTraffic struct {
    Id              uint        `orm:"id,primary"        json:"id"`                //                           
    AdvertiserId    string      `orm:"advertiser_id"     json:"advertiser_id"`     //                           
    MarketplaceId   string      `orm:"marketplace_id"    json:"marketplace_id"`    //                           
    DatasetId       string      `orm:"dataset_id"        json:"dataset_id"`        //                           
    Impressions     int         `orm:"impressions"       json:"impressions"`       //                           
    IdempotencyId   string      `orm:"idempotency_id"    json:"idempotency_id"`    //                           
    KeywordText     string      `orm:"keyword_text"      json:"keyword_text"`      //                           
    TimeWindowStart *gtime.Time `orm:"time_window_start" json:"time_window_start"` // 默认时区是：偏移7.00小时  
    AdGroupId       string      `orm:"ad_group_id"       json:"ad_group_id"`       //                           
    Placement       string      `orm:"placement"         json:"placement"`         //                           
    Cost            float64     `orm:"cost"              json:"cost"`              //                           
    Clicks          int         `orm:"clicks"            json:"clicks"`            //                           
    Currency        string      `orm:"currency"          json:"currency"`          //                           
    AdId            string      `orm:"ad_id"             json:"ad_id"`             //                           
    MatchType       string      `orm:"match_type"        json:"match_type"`        //                           
    CampaignId      string      `orm:"campaign_id"       json:"campaign_id"`       //                           
    KeywordId       string      `orm:"keyword_id"        json:"keyword_id"`        //                           
    CreateDate      *gtime.Time `orm:"create_date"       json:"create_date"`       //                           
}