// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// campaignRuleDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type campaignRuleDao struct {
	internal.CampaignRuleDao
}

var (
	// CampaignRule is globally public accessible object for table campaign_rule operations.
	CampaignRule = campaignRuleDao{
		internal.CampaignRule,
	}
)

// Fill with you ideas below.