// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// feadDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type feadDao struct {
	internal.FeadDao
}

var (
	// Fead is globally public accessible object for table fead operations.
	Fead = feadDao{
		internal.Fead,
	}
)

// Fill with you ideas below.