// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// reportDspConsumerDetailDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type reportDspConsumerDetailDao struct {
	internal.ReportDspConsumerDetailDao
}

var (
	// ReportDspConsumerDetail is globally public accessible object for table report_dsp_consumer_detail operations.
	ReportDspConsumerDetail = reportDspConsumerDetailDao{
		internal.ReportDspConsumerDetail,
	}
)

// Fill with you ideas below.