// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// reportDspCheckDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type reportDspCheckDao struct {
	internal.ReportDspCheckDao
}

var (
	// ReportDspCheck is globally public accessible object for table report_dsp_check operations.
	ReportDspCheck = reportDspCheckDao{
		internal.ReportDspCheck,
	}
)

// Fill with you ideas below.