// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// reportSchduleDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type reportSchduleDao struct {
	internal.ReportSchduleDao
}

var (
	// ReportSchdule is globally public accessible object for table report_schdule operations.
	ReportSchdule = reportSchduleDao{
		internal.ReportSchdule,
	}
)

// Fill with you ideas below.