// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// reportSbConsumerDetailDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type reportSbConsumerDetailDao struct {
	internal.ReportSbConsumerDetailDao
}

var (
	// ReportSbConsumerDetail is globally public accessible object for table report_sb_consumer_detail operations.
	ReportSbConsumerDetail = reportSbConsumerDetailDao{
		internal.ReportSbConsumerDetail,
	}
)

// Fill with you ideas below.