// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// reportErrorDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type reportErrorDao struct {
	internal.ReportErrorDao
}

var (
	// ReportError is globally public accessible object for table report_error operations.
	ReportError = reportErrorDao{
		internal.ReportError,
	}
)

// Fill with you ideas below.