// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// reportCheckDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type reportCheckDao struct {
	internal.ReportCheckDao
}

var (
	// ReportCheck is globally public accessible object for table report_check operations.
	ReportCheck = reportCheckDao{
		internal.ReportCheck,
	}
)

// Fill with you ideas below.