// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// reportBatchDetailDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type reportBatchDetailDao struct {
	internal.ReportBatchDetailDao
}

var (
	// ReportBatchDetail is globally public accessible object for table report_batch_detail operations.
	ReportBatchDetail = reportBatchDetailDao{
		internal.ReportBatchDetail,
	}
)

// Fill with you ideas below.