// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// reportCheckRetryDetailDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type reportCheckRetryDetailDao struct {
	internal.ReportCheckRetryDetailDao
}

var (
	// ReportCheckRetryDetail is globally public accessible object for table report_check_retry_detail operations.
	ReportCheckRetryDetail = reportCheckRetryDetailDao{
		internal.ReportCheckRetryDetail,
	}
)

// Fill with you ideas below.