// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// reportSdCheckDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type reportSdCheckDao struct {
	internal.ReportSdCheckDao
}

var (
	// ReportSdCheck is globally public accessible object for table report_sd_check operations.
	ReportSdCheck = reportSdCheckDao{
		internal.ReportSdCheck,
	}
)

// Fill with you ideas below.