// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// reportSpConsumerDetailDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type reportSpConsumerDetailDao struct {
	internal.ReportSpConsumerDetailDao
}

var (
	// ReportSpConsumerDetail is globally public accessible object for table report_sp_consumer_detail operations.
	ReportSpConsumerDetail = reportSpConsumerDetailDao{
		internal.ReportSpConsumerDetail,
	}
)

// Fill with you ideas below.