// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// reportSpCheckDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type reportSpCheckDao struct {
	internal.ReportSpCheckDao
}

var (
	// ReportSpCheck is globally public accessible object for table report_sp_check operations.
	ReportSpCheck = reportSpCheckDao{
		internal.ReportSpCheck,
	}
)

// Fill with you ideas below.