// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// reportTaskDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type reportTaskDao struct {
	internal.ReportTaskDao
}

var (
	// ReportTask is globally public accessible object for table report_task operations.
	ReportTask = reportTaskDao{
		internal.ReportTask,
	}
)

// Fill with you ideas below.