// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// reportSdConsumerDetailDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type reportSdConsumerDetailDao struct {
	internal.ReportSdConsumerDetailDao
}

var (
	// ReportSdConsumerDetail is globally public accessible object for table report_sd_consumer_detail operations.
	ReportSdConsumerDetail = reportSdConsumerDetailDao{
		internal.ReportSdConsumerDetail,
	}
)

// Fill with you ideas below.