// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// sellerTokenDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sellerTokenDao struct {
	internal.SellerTokenDao
}

var (
	// SellerToken is globally public accessible object for table seller_token operations.
	SellerToken = sellerTokenDao{
		internal.SellerToken,
	}
)

// Fill with you ideas below.