// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// spConversionDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type spConversionDao struct {
	internal.SpConversionDao
}

var (
	// SpConversion is globally public accessible object for table sp_conversion. operations.
	SpConversion = spConversionDao{
		internal.SpConversion,
	}
)

// Fill with you ideas below.