// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"td_report/app/dao/internal"
)

// spTrafficDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type spTrafficDao struct {
	internal.SpTrafficDao
}

var (
	// SpTraffic is globally public accessible object for table sp_traffic operations.
	SpTraffic = spTrafficDao{
		internal.SpTraffic,
	}
)

// Fill with you ideas below.