// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// CampaignDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type CampaignDao struct {
	gmvc.M                                      // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                              // DB is the raw underlying database management object.
	Table   string                              // Table is the table name of the DAO.
	Columns campaignColumns // Columns contains all the columns of Table that for convenient usage.
}

// CampaignColumns defines and stores column names for table campaign.
type campaignColumns struct {
	Id                     string // 主键ID                                                
    AmazonCampaignId       string // 亚马逊主键ID                                          
    ProfileId              string // ProfileID                                             
    AmazonPortfolioId      string // 亚马逊PortfolioId                                     
    Name                   string // 活动名称                                              
    CampaignType           string // 活动类型(sponsoredProducts,sponsoredDisplay)          
    Tactic                 string // 策略                                                  
    TargetingType          string // 目标类型                                              
    State                  string // 广告组状态(enabled:可用;paused:暂停;archived:已归档)  
    BudgetType             string // 预算类型                                              
    DailyBudget            string // 每日预算                                              
    AdFormat               string // sb广告类型                                            
    StartDate              string // 开始时间                                              
    EndDate                string // 结束时间                                              
    BrandEntityId          string // sb 品牌entityId                                       
    PremiumBidAdjustment   string // 溢价投标调整                                          
    BiddingStrategy        string // 投标策略                                              
    TopAdjustment          string // 顶部广告位竞价调整                                    
    ProductPageAdjustment  string // 产品页面调整                                          
    Status                 string // 状态(0:正常;1:禁用)                                   
    AutoStatus             string // 智能优化开关                                          
    ServingStatus          string // 服务状态                                              
    CostType               string // 成本类型展示                                          
    CreatedAt              string //                                                       
    LastUpdate             string //                                                       
    LastUpdateTs           string // 最后更新时间戳                                        
    IsSync                 string // 同步状态(0:待同步;1:已同步)                           
    LastSync               string // 上次同步时间戳                                        
    BidOptimization        string // 0:false 1:true                                        
    BidMultiplier          string // sb出价系数
}

var (
	// Campaign is globally public accessible object for table campaign operations.
	Campaign = CampaignDao{
		M:     g.DB("td_xplatform").Model("campaign").Safe(),
		DB:    g.DB("td_xplatform"),
		Table: "campaign",
		Columns: campaignColumns{
			Id:                    "id",                     
            AmazonCampaignId:      "amazonCampaignId",       
            ProfileId:             "profileId",              
            AmazonPortfolioId:     "amazonPortfolioId",      
            Name:                  "name",                   
            CampaignType:          "campaignType",           
            Tactic:                "tactic",                 
            TargetingType:         "targetingType",          
            State:                 "state",                  
            BudgetType:            "budgetType",             
            DailyBudget:           "dailyBudget",            
            AdFormat:              "adFormat",               
            StartDate:             "startDate",              
            EndDate:               "endDate",                
            BrandEntityId:         "brandEntityId",          
            PremiumBidAdjustment:  "premiumBidAdjustment",   
            BiddingStrategy:       "biddingStrategy",        
            TopAdjustment:         "topAdjustment",          
            ProductPageAdjustment: "productPageAdjustment",  
            Status:                "status",                 
            AutoStatus:            "autoStatus",             
            ServingStatus:         "servingStatus",          
            CostType:              "costType",               
            CreatedAt:             "createdAt",              
            LastUpdate:            "lastUpdate",             
            LastUpdateTs:          "lastUpdateTs",           
            IsSync:                "isSync",                 
            LastSync:              "lastSync",               
            BidOptimization:       "bidOptimization",        
            BidMultiplier:         "bidMultiplier",
		},
	}
)