// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ReportDspCheckDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ReportDspCheckDao struct {
	gmvc.M                        // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                // DB is the raw underlying database management object.
	Table   string                // Table is the table name of the DAO.
	Columns reportDspCheckColumns // Columns contains all the columns of Table that for convenient usage.
}

// ReportDspCheckColumns defines and stores column names for table report_dsp_check.
type reportDspCheckColumns struct {
	Id             string //
	ReportName     string //
	ReportDate     string //
	ProfileId      string //
	Filename       string //
	FileChangedate string // 文件更新时间
	Status         string // 0 不存在 1 存在
	Createdate     string //
	Updatedate     string //
}

var (
	// ReportDspCheck is globally public accessible object for table report_dsp_check operations.
	ReportDspCheck = ReportDspCheckDao{
		M:     g.DB("report").Model("report_dsp_check").Safe(),
		DB:    g.DB("report"),
		Table: "report_dsp_check",
		Columns: reportDspCheckColumns{
			Id:             "id",
			ReportName:     "report_name",
			ReportDate:     "report_date",
			ProfileId:      "profile_id",
			Filename:       "filename",
			FileChangedate: "file_changedate",
			Status:         "status",
			Createdate:     "createdate",
			Updatedate:     "updatedate",
		},
	}
)
