// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ReportTaskDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ReportTaskDao struct {
	gmvc.M                    // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB            // DB is the raw underlying database management object.
	Table   string            // Table is the table name of the DAO.
	Columns reportTaskColumns // Columns contains all the columns of Table that for convenient usage.
}

// ReportTaskColumns defines and stores column names for table report_task.
type reportTaskColumns struct {
	Id         string //
	ReportDate string //
	IsFull     string // 1,0
	AdPlatform string // amazon,google,facebook
	ReportType string // sp,sd,dsp
	TaskType   string // audience,detail,inventory,order,target,ad_group,product_ad,campaign,asin,keyword
	TaskStatus string // initializing,pending,running,succeeded,task_failed,result_wrong
	TimePeriod string // day,month
	DataPath   string //
	LastUpdate string //
}

var (
	// ReportTask is globally public accessible object for table report_task operations.
	ReportTask = ReportTaskDao{
		M:     g.DB("xray_report").Model("report_task").Safe(),
		DB:    g.DB("xray_report"),
		Table: "report_task",
		Columns: reportTaskColumns{
			Id:         "id",
			ReportDate: "report_date",
			IsFull:     "is_full",
			AdPlatform: "ad_platform",
			ReportType: "report_type",
			TaskType:   "task_type",
			TaskStatus: "task_status",
			TimePeriod: "time_period",
			DataPath:   "data_path",
			LastUpdate: "lastUpdate",
		},
	}
)
