// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ReportSchduleDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ReportSchduleDao struct {
	gmvc.M                       // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB               // DB is the raw underlying database management object.
	Table   string               // Table is the table name of the DAO.
	Columns reportSchduleColumns // Columns contains all the columns of Table that for convenient usage.
}

// ReportSchduleColumns defines and stores column names for table report_schdule.
type reportSchduleColumns struct {
	Id             string //
	Batch          string //
	ReportType     string //
	ReportnameList string //
	ReportDate     string //
	CreateDate     string //
	ProfileNum     string //
	SchduleType    string // 调度类型 0:今天和昨天 1:14天内 2: 半月调度3:整个月调度4检测文件调度
	EndTime        string // 结束时间
	StartTime      string // 开始时间
}

var (
	// ReportSchdule is globally public accessible object for table report_schdule operations.
	ReportSchdule = ReportSchduleDao{
		M:     g.DB("report").Model("report_schdule").Safe(),
		DB:    g.DB("report"),
		Table: "report_schdule",
		Columns: reportSchduleColumns{
			Id:             "id",
			Batch:          "batch",
			ReportType:     "report_type",
			ReportnameList: "reportname_list",
			ReportDate:     "report_date",
			CreateDate:     "create_date",
			ProfileNum:     "profile_num",
			SchduleType:    "schdule_type",
			EndTime:        "end_time",
			StartTime:        "start_time",
		},
	}
)
