// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ReportBatchDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ReportBatchDao struct {
	gmvc.M                     // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB             // DB is the raw underlying database management object.
	Table   string             // Table is the table name of the DAO.
	Columns reportBatchColumns // Columns contains all the columns of Table that for convenient usage.
}

// ReportBatchColumns defines and stores column names for table report_batch.
type reportBatchColumns struct {
	Id         string //
	Batch      string // 批次号
	Paramas    string // 参数
	Status     string // 状态 1 创建 2 成功 3 失败
	CreateTime string // 创建时间
	UpdateTime string // 修改时间
	IsCheck    string // 默认0 已处理1
}

var (
	// ReportBatch is globally public accessible object for table report_batch operations.
	ReportBatch = ReportBatchDao{
		M:     g.DB("report").Model("report_batch").Safe(),
		DB:    g.DB("report"),
		Table: "report_batch",
		Columns: reportBatchColumns{
			Id:         "id",
			Batch:      "batch",
			Paramas:    "paramas",
			Status:     "status",
			CreateTime: "create_time",
			UpdateTime: "update_time",
			IsCheck:    "is_check",
		},
	}
)
