// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ReportErrorDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ReportErrorDao struct {
	gmvc.M                     // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB             // DB is the raw underlying database management object.
	Table   string             // Table is the table name of the DAO.
	Columns reportErrorColumns // Columns contains all the columns of Table that for convenient usage.
}

// ReportErrorColumns defines and stores column names for table report_error.
type reportErrorColumns struct {
	Id          string //
	ErrorType   string // 错误类型
	ErrorReason string // 错误信息
	KeyParamas  string // 关键参数json,除部分参数明确外其他的不明确参数
	CreateDate  string //
	ReportType  string //
	ReportName  string //
	ReportDate  string //
	ProfileId   string //
	Extrant     string // 额外类别，区分sd的t200 ,t300等
}

var (
	// ReportError is globally public accessible object for table report_error operations.
	ReportError = ReportErrorDao{
		M:     g.DB("report").Model("report_error").Safe(),
		DB:    g.DB("report"),
		Table: "report_error",
		Columns: reportErrorColumns{
			Id:          "id",
			ErrorType:   "error_type",
			ErrorReason: "error_reason",
			KeyParamas:  "key_paramas",
			CreateDate:  "create_date",
			ReportType:  "report_type",
			ReportName:  "report_name",
			ReportDate:  "report_date",
			ProfileId:   "profile_id",
			Extrant:     "extrant",
		},
	}
)
