// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ReportSdConsumerDetailDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ReportSdConsumerDetailDao struct {
	gmvc.M                                // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                        // DB is the raw underlying database management object.
	Table   string                        // Table is the table name of the DAO.
	Columns reportSdConsumerDetailColumns // Columns contains all the columns of Table that for convenient usage.
}

// ReportSdConsumerDetailColumns defines and stores column names for table report_sd_consumer_detail.
type reportSdConsumerDetailColumns struct {
	Id         string //
	CtxId      string // 上下文链路追踪id
	CreateTime string // 创建时间
	ReportName string //
	ProfileId  string //
	Status     string // 0 默认 1 成功 2 失败
	ReportDate string //
	Error      string //
	Batch      string //
	CostTime   string // 花费的时间秒
	UpdateTime string // 修改时间
}

var (
	// ReportSdConsumerDetail is globally public accessible object for table report_sd_consumer_detail operations.
	ReportSdConsumerDetail = ReportSdConsumerDetailDao{
		M:     g.DB("report").Model("report_sd_consumer_detail").Safe(),
		DB:    g.DB("report"),
		Table: "report_sd_consumer_detail",
		Columns: reportSdConsumerDetailColumns{
			Id:         "id",
			CtxId:      "ctx_id",
			CreateTime: "create_time",
			ReportName: "report_name",
			ProfileId:  "profile_id",
			Status:     "status",
			ReportDate: "report_date",
			Error:      "error",
			Batch:      "batch",
			CostTime:   "cost_time",
			UpdateTime: "update_time",
		},
	}
)
