// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SellerProfileDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SellerProfileDao struct {
	gmvc.M                                      // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                              // DB is the raw underlying database management object.
	Table   string                              // Table is the table name of the DAO.
	Columns sellerProfileColumns // Columns contains all the columns of Table that for convenient usage.
}

// SellerProfileColumns defines and stores column names for table seller_profile.
type sellerProfileColumns struct {
	Id                   string // 自增ID                             
    TokenId              string // TokenID                            
    Region               string // 地区(NA:美区;EU:欧区;FE:日韩区)    
    ProfileId            string // ProfileID                          
    EntityName           string // 实体名称                           
    DspProfileId         string // DSP profileId                      
    DspAdvertiserId      string // DSP advertiserId                   
    CountryCode          string // 国家代码                           
    CurrencyCode         string // 货币代码                           
    Timezone             string // 时区                               
    MarketplaceStringId  string //                                    
    EntityId             string // 实体ID                             
    Type                 string // 类型(seller:经销商;agency:代理商)  
    IsAuto               string //                                    
    Status               string // 状态(0:正常;1:禁用)                
    CreatedAt            string // 最后更新时间                       
    LastUpdate           string // 同步状态
}

var (
	// SellerProfile is globally public accessible object for table seller_profile operations.
	SellerProfile = SellerProfileDao{
		M:     g.DB("default").Model("seller_profile").Safe(),
		DB:    g.DB("default"),
		Table: "seller_profile",
		Columns: sellerProfileColumns{
			Id:                  "id",                   
            TokenId:             "tokenId",              
            Region:              "region",               
            ProfileId:           "profileId",            
            EntityName:          "entityName",           
            DspProfileId:        "dspProfileId",         
            DspAdvertiserId:     "dspAdvertiserId",      
            CountryCode:         "countryCode",          
            CurrencyCode:        "currencyCode",         
            Timezone:            "timezone",             
            MarketplaceStringId: "marketplaceStringId",  
            EntityId:            "entityId",             
            Type:                "type",                 
            IsAuto:              "isAuto",               
            Status:              "status",               
            CreatedAt:           "createdAt",            
            LastUpdate:          "lastUpdate",
		},
	}
)