// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SellerClientDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SellerClientDao struct {
	gmvc.M                      // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB              // DB is the raw underlying database management object.
	Table   string              // Table is the table name of the DAO.
	Columns sellerClientColumns // Columns contains all the columns of Table that for convenient usage.
}

// SellerClientColumns defines and stores column names for table seller_client.
type sellerClientColumns struct {
	Id           string //
	ClientId     string //
	ClientSecret string //
	IsCurrent    string // 新授权使用标记, 1-正在使用, 0-未使用
	CreatedAt    string //
	LastUpdate   string //
}

var (
	// SellerClient is globally public accessible object for table seller_client operations.
	SellerClient = SellerClientDao{
		M:     g.DB("td_xplatform").Model("seller_client").Safe(),
		DB:    g.DB("td_xplatform"),
		Table: "seller_client",
		Columns: sellerClientColumns{
			Id:           "id",
			ClientId:     "clientId",
			ClientSecret: "clientSecret",
			IsCurrent:    "isCurrent",
			CreatedAt:    "createdAt",
			LastUpdate:   "lastUpdate",
		},
	}
)
