// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SellerTokenDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SellerTokenDao struct {
	gmvc.M                                      // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                              // DB is the raw underlying database management object.
	Table   string                              // Table is the table name of the DAO.
	Columns sellerTokenColumns // Columns contains all the columns of Table that for convenient usage.
}

// SellerTokenColumns defines and stores column names for table seller_token.
type sellerTokenColumns struct {
	Id              string //                                               
    UserId          string //                                               
    Region          string //                                               
    Country         string // 已勾选国家                                    
    SellerSN        string //                                               
    Nickname        string //                                               
	ClientId        string // clientId
    RefreshToken    string //
    AccessToken     string //                                               
    Expires         string //                                               
    SpRefreshToken  string // SPAPI refresh token                           
    SpAccessToken   string // SPAPI access token                            
    SpExpires       string // SPAPI过期时间                                 
    Code            string //                                               
    Params          string //                                               
    Status          string // 1 - 启用，2 - 删除，3 - 暂存                  
    IsPPC           string // ppc授权状态，0：未授权 1：已授权              
    IsSP            string // SPAPI授权状态，0：未授权 1：已授权 2：已过期  
    IsMWS           string // mws授权状态，0：未授权 1：已授权              
    CreatedAt       string //                                               
    LastUpdate      string //
}

var (
	// SellerToken is globally public accessible object for table seller_token operations.
	SellerToken = SellerTokenDao{
		M:     g.DB("default").Model("seller_token").Safe(),
		DB:    g.DB("default"),
		Table: "seller_token",
		Columns: sellerTokenColumns{
			Id:             "id",              
            UserId:         "userId",          
            Region:         "region",          
            Country:        "country",         
            SellerSN:       "sellerSN",        
            Nickname:       "nickname",
			ClientId:       "clientId",
            RefreshToken:   "refreshToken",
            AccessToken:    "accessToken",     
            Expires:        "expires",         
            SpRefreshToken: "spRefreshToken",  
            SpAccessToken:  "spAccessToken",   
            SpExpires:      "spExpires",       
            Code:           "code",            
            Params:         "params",          
            Status:         "status",          
            IsPPC:          "isPPC",           
            IsSP:           "isSP",            
            IsMWS:          "isMWS",           
            CreatedAt:      "createdAt",       
            LastUpdate:     "lastUpdate",
		},
	}
)