// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SpTrafficDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SpTrafficDao struct {
	gmvc.M                                      // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                              // DB is the raw underlying database management object.
	Table   string                              // Table is the table name of the DAO.
	Columns spTrafficColumns // Columns contains all the columns of Table that for convenient usage.
}

// SpTrafficColumns defines and stores column names for table sp_traffic.
type spTrafficColumns struct {
	Id               string //                           
    AdvertiserId     string //                           
    MarketplaceId    string //                           
    DatasetId        string //                           
    Impressions      string //                           
    IdempotencyId    string //                           
    KeywordText      string //                           
    TimeWindowStart  string // 默认时区是：偏移7.00小时  
    AdGroupId        string //                           
    Placement        string //                           
    Cost             string //                           
    Clicks           string //                           
    Currency         string //                           
    AdId             string //                           
    MatchType        string //                           
    CampaignId       string //                           
    KeywordId        string //                           
    CreateDate       string //
}

var (
	// SpTraffic is globally public accessible object for table sp_traffic operations.
	SpTraffic = SpTrafficDao{
		M:     g.DB("xray_report").Model("sp_traffic").Safe(),
		DB:    g.DB("xray_report"),
		Table: "sp_traffic",
		Columns: spTrafficColumns{
			Id:              "id",                 
            AdvertiserId:    "advertiser_id",      
            MarketplaceId:   "marketplace_id",     
            DatasetId:       "dataset_id",         
            Impressions:     "impressions",        
            IdempotencyId:   "idempotency_id",     
            KeywordText:     "keyword_text",       
            TimeWindowStart: "time_window_start",  
            AdGroupId:       "ad_group_id",        
            Placement:       "placement",          
            Cost:            "cost",               
            Clicks:          "clicks",             
            Currency:        "currency",           
            AdId:            "ad_id",              
            MatchType:       "match_type",         
            CampaignId:      "campaign_id",        
            KeywordId:       "keyword_id",         
            CreateDate:      "create_date",
		},
	}
)